title: EveryGlobal
author:
  name: 'Won Lee'
  email: albanbailly@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects:
  - '1420 Boren Ave, APT 210'
blog:
  route: /blog
